### ISSUE TITLE
Building haddock doc fails

### ISSUE THREAD

**Issue by phile314** [UU-ComputerScience/uhc#28]
The following fails:
<pre>$ ./configure
....
$ make 101/hdoc
....
Building UHC-Compiler-1.1...
Preprocessing library UHC-Compiler-1.1...

UHC/Compiler/AbstractCore.hs:89:8:
    Could not find module `UHC.Compiler.Ty'
    Use -v to see a list of the files searched for.
make[2]: *** [/home/philipp/Projects/uu/uhc/uhc/EHC/install-for-build/ins-flg-UHC-Compiler] Error 1
make[2]: Leaving directory `/home/philipp/Projects/uu/uhc/uhc/EHC'
make[1]: *** [ehc-haddock-variant] Error 2
make[1]: Leaving directory `/home/philipp/Projects/uu/uhc/uhc/EHC'
make: *** [101/hdoc] Error 2</pre>

I also checked manually if the file Ty.hs exists, and it was missing from the build/101/lib-ehc/UHC/Compiler/ directory.

**Comment by atzedijkstra** [comment]
Since this is currently not supported, the issue is closed.
