### ISSUE TITLE
ANormal Trf is not always run, causes runtime errors

### ISSUE THREAD

**Issue by phile314** [UU-ComputerScience/uhc#36]
If I compile binary Core Code, the ANormal transformation is not always run. This leads to crashes at
runtime or wrong output.

It looks like ANormal is never applied to the Main-module, and only sometimes to non-Main modules.

A small example reproducing the error is https://github.com/phile314/uhc/blob/3fb2d82f26a2afe1f60b4b7e1855d7bb5d404053/EHC/demo/CoreApi.hs .
Commenting out line 33, and instead using line 35 reproduces the error (prints the empty string instead of "HelloWorld").

Looks to me like the problem is in Core/Trf.chs, it doesn't seem to apply all transformations. With dump-core-stages=1 I get the following files:
CoreApiProg.tcr-permodule-10-let-defbefuse
CoreApiProg.tcr-permodule-1-initial
CoreApiProg.tcr-permodule-2-fix-postparse
CoreApiProg.tcr-permodule-3-let-defbefuse
CoreApiProg.tcr-permodule-4-let-flatstr
CoreApiProg.tcr-permodule-5-inl-letali
CoreApiProg.tcr-permodule-6-elim-trivapp
CoreApiProg.tcr-permodule-7-const-prop
CoreApiProg.tcr-permodule-8-inl-letali
CoreApiProg.tcr-permodule-9-elim-trivapp

**Comment by atzedijkstra** [comment]
This did happen when Core files were read. A check is now included to find out whether a ANormal transformation is still required.

**Comment by phile314** [comment]
This means I can remove the " include a non-global lambda expression" work-around from the Core API, right?

**Comment by atzedijkstra** [comment]
Yes, but please verify this as I have tested it with small examples only.

Atze

> On  27 Feb, 2015, at 12:24 , Philipp Hausmann <notifications@github.com> wrote:
> 
> This means I can remove the " include a non-global lambda expression" work-around from the Core API, right?
> 
> —
> Reply to this email directly or view it on GitHub.
> 


                - Atze -

Atze Dijkstra, Department of Information and Computing Sciences. /|\
Utrecht University, PO Box 80089, 3508 TB Utrecht, Netherlands. / | \
Tel.: +31-30-2534118/1454 | WWW  : http://www.cs.uu.nl/~atze . /--|  \
Fax : +31-30-2513971 .... | Email: atze@uu.nl ............... /   |___\
