### ISSUE TITLE
Add Core Exports for Datatypes

### ISSUE THREAD

**Issue by phile314** [UU-ComputerScience/uhc#43]
Currently, only functions can be exported by Core modules and used by other Core modules. Datatypes cannot be exported. There is a workaround using -Operwholecore, but this makes compilation much slower.

Export-statements similar to the function-exports should be added to Core to improve this. I guess this
requires adding a new export_datatype keyword or similar, as I think function and datatype names could
possibly collide in Core. For my use-case, it doesn't matter if export-granularity is per datatype or per constructor.

Note: It is unlikely that this is implemented soon

**Comment by atzedijkstra** [comment]
There is now an export mechanism for datatypes.
