### ISSUE TITLE
uhc-light-1.1.8.5 doesn't compile with GHC 7.8.4

### ISSUE THREAD

**Issue by peti** [UU-ComputerScience/uhc#44]
Citing from http://hydra.cryp.to/build/527123/nixlog/2/raw:

    Preprocessing executable 'uhcl' for uhc-light-1.1.8.5...

    src-main/EHC.hs:4:8:
        Could not find module ‘UHC.Light.Compiler.Opts’
        it is a hidden module in the package ‘uhc-light-1.1.8.5’
        Use -v to see a list of the files searched for.

**Comment by atzedijkstra** [comment]
Fixed with 1.1.8.6 (using ghc 7.8.3)
