### ISSUE TITLE
uhc-light-1.1.8.6 has Haddock syntax errors

### ISSUE THREAD

**Issue by peti** [UU-ComputerScience/uhc#45]
Citing from http://hydra.cryp.to/build/527376/log/raw:

    Running Haddock for uhc-light-1.1.8.6...
    Running hscolour for uhc-light-1.1.8.6...
    Preprocessing library uhc-light-1.1.8.6...
    Preprocessing executable 'uhcl' for uhc-light-1.1.8.6...
    Preprocessing executable 'uhcr' for uhc-light-1.1.8.6...
    Preprocessing library uhc-light-1.1.8.6...

    src/ehc/CoreRun/Prim.chs:132:3:
        parse error on input ‘-- | RP_readFile                  -- :: FilePath -> IO String
      -- | RP_writeFile                 -- :: FilePath -> String -> IO ()
      -- | RP_appendFile                -- :: FilePath -> String -> IO ()’

**Comment by atzedijkstra** [comment]
This will be fixed with the following release, part of next commit.

**Comment by atzedijkstra** [comment]
Should be ok now.
