### ISSUE TITLE
Create git tags for releases

### ISSUE THREAD

**Issue by phile314** [UU-ComputerScience/uhc#48]
It would be nice if there are git tags for (future) released versions. Would make it easier to refer to specific versions in manuals etc.

how to tag:
git tag v1.0.0.0
git push origin v1.0.0.0

Tagged versions will also appear in the relase tab on github:
https://github.com/UU-ComputerScience/uhc/releases

What do you think?

**Comment by atzedijkstra** [comment]
This can easily be built into the Makefile version bumping targets, so I'll cater for that with the next version.

Atze

> On  27 Feb, 2015, at 12:34 , Philipp Hausmann <notifications@github.com> wrote:
> 
> It would be nice if there are git tags for (future) released versions. Would make it easier to refer to specific versions in manuals etc.
> 
> how to tag:
> git tag v1.0.0.0
> git push origin v1.0.0.0
> 
> Tagged versions will also appear in the relase tab on github:
> https://github.com/UU-ComputerScience/uhc/releases
> 
> What do you think?
> 
> —
> Reply to this email directly or view it on GitHub.
> 


                - Atze -

Atze Dijkstra, Department of Information and Computing Sciences. /|\
Utrecht University, PO Box 80089, 3508 TB Utrecht, Netherlands. / | \
Tel.: +31-30-2534118/1454 | WWW  : http://www.cs.uu.nl/~atze . /--|  \
Fax : +31-30-2513971 .... | Email: atze@uu.nl ............... /   |___\
