### ISSUE TITLE
Add support for GHC 7.10

### ISSUE THREAD

**Issue by phile314** [UU-ComputerScience/uhc#54]
Add support for GHC 7.10 to UHC and all dependencies. The following uhc-specific tools/libs need to be checked:

-uulib (done)
-uhc-util (done ~~fails, http://hydra.cryp.to/build/698022/log~~)
-uuagc (done)
-uuagc-cabal (done ~~fails, http://hydra.cryp.to/build/689052/log~~)
~~-uuagc-bootstrap (fails, http://hydra.cryp.to/build/699943/log )~~
-shuffle (done ~~fails, http://hydra.cryp.to/build/722468/log/tail-reload~~ )
-uhc (done)

@atze @jbransen There is no public repo for uuagc/uuagc-cabal/uuagc-bootstrap as far as I know. Is it maybe possible to move these projects to Github too?

I will take a look at uhc-util later this week. If uuagc/uuagc-cabal/uuagc-bootstrap are moved to Github, I could also look at those.

If anyone else wants to work on any of these, maybe post a short comment here.

**Comment by jbransen** [comment]
The UUAGC project (including uuagc-cabal and uuagc-bootstrap) is at https://svn.science.uu.nl/repos/project.STEC.uuagc/uuagc/trunk/ which is public. I see no reason to move to github (actually, since this url has been in use for quite a while I'd prefer keeping the SVN version).

**Comment by atzedijkstra** [comment]
Cooperation, that is fixes by others submitted via pull requests etc, is easier with git(hub).

Atze

> On  31 Mar, 2015, at 14:08 , Jeroen Bransen <notifications@github.com> wrote:
> 
> The UUAGC project (including uuagc-cabal and uuagc-bootstrap) is at https://svn.science.uu.nl/repos/project.STEC.uuagc/uuagc/trunk/ which is public. I see no reason to move to github (actually, since this url has been in use for quite a while I'd prefer keeping the SVN version).
> 
> —
> Reply to this email directly or view it on GitHub.
> 


                - Atze -

Atze Dijkstra, Department of Information and Computing Sciences. /|\
Utrecht University, PO Box 80089, 3508 TB Utrecht, Netherlands. / | \
Tel.: +31-30-2534118/1454 | WWW  : http://www.cs.uu.nl/~atze . /--|  \
Fax : +31-30-2513971 .... | Email: atze@uu.nl ............... /   |___\

**Comment by jbransen** [comment]
SVN patches sent by e-mail also work fine, especially in a project with low number of users such as uuagc, but @atzedijkstra you are in charge so if you want to move the project to github then go ahead.

**Comment by atzedijkstra** [comment]
uhc-util should be ok now.

A

> On  31 Mar, 2015, at 13:47 , Philipp Hausmann <notifications@github.com> wrote:
> 
> Add support for GHC 7.10 to UHC and all dependencies. The following uhc-specific tools/libs need to be checked:
> 
> -uulib (done)
> -uhc-util (fails, http://hydra.cryp.to/build/698022/log )
> -uuagc
> -uuagc-cabal (fails, http://hydra.cryp.to/build/689052/log )
> -uuagc-bootstrap (fails, http://hydra.cryp.to/build/699943/log )
> 
> @atze @jbransen There is no public repo for uuagc/uuagc-cabal/uuagc-bootstrap as far as I know. Is it maybe possible to move these projects to Github too?
> 
> I will take a look at uhc-util later this week. If uuagc/uuagc-cabal/uuagc-bootstrap are moved to Github, I could also look at those.
> 
> If anyone else wants to work on any of these, maybe post a short comment here.
> 
> —
> Reply to this email directly or view it on GitHub.
> 


                - Atze -

Atze Dijkstra, Department of Information and Computing Sciences. /|\
Utrecht University, PO Box 80089, 3508 TB Utrecht, Netherlands. / | \
Tel.: +31-30-2534118/1454 | WWW  : http://www.cs.uu.nl/~atze . /--|  \
Fax : +31-30-2513971 .... | Email: atze@uu.nl ............... /   |___\

**Comment by phile314** [comment]
Thanks Atze. I just sent the patch for uuagc/uuagc-cabal to the hut-developers mailing list.

**Comment by phile314** [comment]
UHC compilation on GHC 7.10 works with commit https://github.com/UU-ComputerScience/uhc/commit/1ab943067430999a30efd5dc06463ebc63b50375 .

I haven't tried building uhc-light yet, not sure if I get round to that this week, but I don't expect many problems there.

**Comment by atzedijkstra** [comment]
I am checking uhc-light now, has issues w.r.t. visibility of constructor ‘Alt’…

A

> On  30 Apr, 2015, at 12:10 , Philipp Hausmann <notifications@github.com> wrote:
> 
> UHC compilation on GHC 7.10 works with commit 1ab9430 .
> 
> I haven't tried building uhc-light yet, not sure if I get round to that this week, but I don't expect many problems there.
> 
> —
> Reply to this email directly or view it on GitHub.
> 


                - Atze -

Atze Dijkstra, Department of Information and Computing Sciences. /|\
Utrecht University, PO Box 80089, 3508 TB Utrecht, Netherlands. / | \
Tel.: +31-30-2534118/1454 | WWW  : http://www.cs.uu.nl/~atze . /--|  \
Fax : +31-30-2513971 .... | Email: atze@uu.nl ............... /   |___\

**Comment by phile314** [comment]
Works for me, closing the issue.
