### ISSUE TITLE
UHC git head doesn't build without ruler

### ISSUE THREAD

**Issue by phile314** [UU-ComputerScience/uhc#61]
Continuing our earlier email discussion, I tried to build current UHC git head but this fails on my machine.
Configure works, but the makefile seems to cause problems:

<pre>
./configure --prefix /tmp/test-uhc
... snip ...
Version : 1.1.9.1
GIT hash: master@fa16f901f7
Installation/build summary.
  host                          : x86_64-unknown-linux-gnu
  prefix                        : /tmp/test-uhc
  build suffix                  : 
  hardbaked aspects             : 
Required:
  uuagc is available?           : yes
    version                     : Attribute Grammar compiler / HUT project. Version 0.9.51
    command for uuagc           : /home/philipp/.nix-profile/bin/uuagc
  shuffle is available?         : yes
    version                     : 0.1.3.3
    command for shuffle         : /home/philipp/.nix-profile/bin/shuffle
  ghc is available?             : yes
    version                     : 7.8.4
    command for ghc             : /home/philipp/.nix-profile/bin/ghc
    command for ghc raw         : /home/philipp/.nix-profile/bin/ghc
    libraries:
      required and present      : filepath-1.3.0.2 process-1.2.0.0 array-0.5.0.0 containers-0.5.5.1 directory-1.2.1.0 transformers-0.3.0.0 mtl-2.1.3.1 base-4.7.0.2 uhc-util-0.1.5.6 hashable-1.2.3.0 binary-0.7.1.0 network-2.6.0.2 uulib-0.9.20 syb-0.4.2 vector-0.10.12.2 fgl-5.5.0.1 
  gcc is available?             : yes
    version                     : 4.9.2
    command for gcc             : /usr/bin/gcc
    uhc options to gcc          :  
  cpp is available?             : yes
    version                     : cpp (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6) Copyright (C) 2014 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    command for cpp             : /usr/bin/cpp
    uhc options to cpp          :   -D__STDC__
  MP library                    : ltm
Required (or optional) but not (yet) or during build enforced:
  cabal base dependencies       :  fgl uulib>=0.9.19 hashable>=1.1&&<1.3 uhc-util>=0.1.6.1&&<0.1.7 base>=4.7&&<5  vector syb network binary mtl transformers directory containers array process filepath
  cabal extra dependencies      : 
  build tool dependencies       : shuffle>=0.1.3.1 uuagc>=0.9.50.2 
  (optional) build tool dpdcies : 
Other:
  haddock is available?         : yes
    version                     : Haddock version 2.14.3, (c) Simon Marlow 2006
    command for haddock         : /home/philipp/.nix-profile/bin/haddock
  ruler is available?           : no
Absolute location of directories:
  ehc repository                : /home/philipp/Projects/uhc/uhc2/EHC
  ehc repository raw            : /home/philipp/Projects/uhc/uhc2/EHC
  unix root prefix raw          : 
$ make
src/ehc/files1.mk:468: *** multiple target patterns.  Stop.
</pre>

The commit introducing this problem:
<pre>
f0d85858ca1d309f57edda08d9f3a55c5b54a5ec is the first bad commit
commit f0d85858ca1d309f57edda08d9f3a55c5b54a5ec
Author: Atze Dijkstra <atzedijkstra@gmail.com>
Date:   Wed Sep 16 16:58:09 2015 +0200

    fixing debugging stuff for type checker, fix for type pretty print which did incorrectly print tyvars

</pre>

I used a freshly cloned git repository, so there should be no old files lying around.

**Comment by phile314** [comment]
So I investigated a bit more, and the changed configure test for ruler seems to be the problem. If I give a dummy ruler binary, the build at least starts:

<pre>
$ ./configure --prefix /tmp/test-uhc --with-ruler=/bin/true
... snip ...
Version : 1.1.9.1
GIT hash: master@fa16f901f7
Installation/build summary.
  host                          : x86_64-unknown-linux-gnu
  prefix                        : /tmp/test-uhc
  build suffix                  : 
  hardbaked aspects             : 
Required:
  uuagc is available?           : yes
    version                     : Attribute Grammar compiler / HUT project. Version 0.9.51
    command for uuagc           : /home/philipp/.nix-profile/bin/uuagc
  shuffle is available?         : yes
    version                     : 0.1.3.3
    command for shuffle         : /home/philipp/.nix-profile/bin/shuffle
  ghc is available?             : yes
    version                     : 7.8.4
    command for ghc             : /home/philipp/.nix-profile/bin/ghc
    command for ghc raw         : /home/philipp/.nix-profile/bin/ghc
    libraries:
      required and present      : filepath-1.3.0.2 process-1.2.0.0 array-0.5.0.0 containers-0.5.5.1 directory-1.2.1.0 transformers-0.3.0.0 mtl-2.1.3.1 base-4.7.0.2 uhc-util-0.1.5.6 hashable-1.2.3.0 binary-0.7.1.0 network-2.6.0.2 uulib-0.9.20 syb-0.4.2 vector-0.10.12.2 fgl-5.5.0.1 
  gcc is available?             : yes
    version                     : 4.9.2
    command for gcc             : /usr/bin/gcc
    uhc options to gcc          :  
  cpp is available?             : yes
    version                     : cpp (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6) Copyright (C) 2014 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    command for cpp             : /usr/bin/cpp
    uhc options to cpp          :   -D__STDC__
  MP library                    : ltm
Required (or optional) but not (yet) or during build enforced:
  cabal base dependencies       :  fgl uulib>=0.9.19 hashable>=1.1&&<1.3 uhc-util>=0.1.6.1&&<0.1.7 base>=4.7&&<5  vector syb network binary mtl transformers directory containers array process filepath
  cabal extra dependencies      : 
  build tool dependencies       : shuffle>=0.1.3.1 uuagc>=0.9.50.2 
  (optional) build tool dpdcies : ruler>=0.4.0.1 
Other:
  haddock is available?         : yes
    version                     : Haddock version 2.14.3, (c) Simon Marlow 2006
    command for haddock         : /home/philipp/.nix-profile/bin/haddock
  ruler is available?           : yes
    version                     : true (GNU coreutils) 8.22
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jim Meyering.
    command for ruler           : /bin/true
Absolute location of directories:
  ehc repository                : /home/philipp/Projects/uhc/uhc2/EHC
  ehc repository raw            : /home/philipp/Projects/uhc/uhc2/EHC
  unix root prefix raw          : 
$ make
make INCLUDE_DERIVED_MK=yes EHC_VARIANT=`echo install/101/bin/ehc | sed -n -e 's+install/\([0-9_]*\)/bin/ehc.*+\1+p'` ehc-variant
make[1]: Entering directory '/home/philipp/Projects/uhc/uhc2/EHC'
mkdir -p build/101/lib-ehc/UHC/Compiler/
/home/philipp/.nix-profile/bin/shuffle src/ehc/files-ag-d.dep --dep \
  --depnameprefix=EHC_ \
  --depsrcvar=SRC_EHC_PREFIX \
  --depdstvar=EHC_BLD_LIB_HS_VARIANT_PREFIX \
  --depmainvar=EHC_AG_D_MAIN_SRC_CAG \
  --depdpdsvar=EHC_AG_D_DPDS_SRC_CAG \
  --deporigdpdsvar=EHC_AG_D_ODPDS_SRC_CAG \
  --depderivdpdsvar=EHC_AG_D_DDPDS_DERIV_AG \
  --depbase=src/ehc/ \
  --depterm="EHRulerRules>" \
  --depign="EHRulerRules EHRulerRules.cag" \
    > build/101/lib-ehc/UHC/Compiler/files-ag-d-dep.mk
.... snip ....
</pre>

**Comment by atzedijkstra** [comment]
Ok, that makes sense, as dependencies end up being wrongly build due to absence of ruler. I think the best fix is to remove such dependencies. I’ll look at it, the previous mail did make me go in a wrong direction.

Thx!

A

**Comment by atzedijkstra** [comment]
Ok, I did push a quick patch… Please try again…

A

**Comment by phile314** [comment]
Git head ( a81d5834be ) builds fine now. Thanks.

I also tested the Agda/UHC combination with that version, and everything worked fine.

Philipp
