### ISSUE TITLE
Compile error: uhc-util v0.1.6.4 or higher missing

### ISSUE THREAD

**Issue by tobi512** [UU-ComputerScience/uhc#62]
Hi, 
just tried to compile UHC and after fixing missing uuagc with the solution of #4 i'm now running into compilation failure because uhc-util v0.1.6.4 or higher is missing.
`At least the following dependencies are missing: uhc-util >=0.1.6.4 && <0.1.7`
Currently installed version of uhc-util is 0.1.6.3, where/how can i get the new version? @atzedijkstra 

Hopefully, using the master of UHC was the right way to compile as the releases (e.g. 1.0.0) seem a bit outdated...

Sincerely, 
Tobias

**Comment by atzedijkstra** [comment]
Hi Tobias,

de repo’s 

https://github.com/UU-ComputerScience/uhc <https://github.com/UU-ComputerScience/uhc>
https://github.com/UU-ComputerScience/uhc-util <https://github.com/UU-ComputerScience/uhc-util>

are kept/updated in sync, so if you clone uhc from the above repo, it usually is also necessary to use the above uhc-util repo, which has the correct version number. Likewise, the hackage distributions are also kept in sync.

cheers,
Atze

**Comment by tobi512** [comment]
Hi Atze, 
thanks for your quick answer!
However i'm struggling with the installation of uhc-util a bit:
`runhaskell Setup.hs configure` tells me some libraries are missing

`Configuring uhc-util-0.1.6.4...
Setup.hs: At least the following dependencies are missing:
fclabels >=2.0.2, time-compat >=0.1.0.1, uulib >=0.9.19`

Seems like a path issue, since i have the libs in the rights versions installed via cabal:
`All the requested packages are already installed:
uulib-0.9.21` etc.

My $PATH-variable is expanded to `PATH="$HOME/Library/Haskell/bin:$PATH"` but uulib and the other dependencies are installed somewhere else (in `~/Library/Haskell/ghc-7.10.2-x86_64/lib/uulib-0.9.21`for example but i didnt find any binaries named `uulib`...)

Any ideas what i'm doing wrong? @atzedijkstra  :smiley: 

Sincerely,
Tobias

**Comment by atzedijkstra** [comment]
Hi Tobias,

I am not really sure what happens on your system, but it looks like your ghc installation is not ok? Maybe something like ghc-pkg recache might help… In situations like this I usually end up trying such fixes; if that still not works I reinstall the platform, after uninstalling ghc and throwing away the content of various cabal directories (to avoid later version conflicts).

regards,
Atze

**Comment by tobi512** [comment]
Hi Atze, 
just reinstalled the whole GHC package and cabal, but same problem with the dependencies again...
Easiest solution would be if you could upload `uhc-util-0.1.6.4` to hackage.haskell.com so i could just install it via cabal from there, no?!
Would be great if we could give that a try.

Dank je wel! :smile: 
Tobias
