### ISSUE TITLE
Missing new version announce?

### ISSUE THREAD

**Issue by asr** [UU-ComputerScience/uhc#64]
How can I know that a new version of UHC was released? Note that the information in [releases](https://github.com/UU-ComputerScience/uhc/releases) is outdated.

**Comment by atzedijkstra** [comment]
Already for some time I add tags to the github versions/releases, but I recently found out that github does not show them. The intent is/was to let tags correspond to the versions of uhc-light in hackage. I still have to sort out why assigned tags are not visible at github.

regards,
Atze

**Comment by phile314** [comment]
I'm not sure, but does "git push" also push tags to github by default? I think one has to use "git push --tags" to push all tags, or "git push THE_TAG_NAME" to push one specific tag. Does that help?

**Comment by atzedijkstra** [comment]
Ah yes, git push --tags does the job (done now). There are no explicit release notes currently as I maintain a changelog, but it should be relatively easy to (automatically) copy the changelog description for a version to the release notes.

A

**Comment by asr** [comment]
Now that the tags were fixed, I can subscribe to the [release feed](https://github.com/UU-ComputerScience/uhc/releases.atom)  for knowing that a new version of UHC was released. Thanks!
