### ISSUE TITLE
UHC Windows support

### ISSUE THREAD

**Issue by phile314** [UU-ComputerScience/uhc#65]
The question whether UHC supports Windows came up because of agda/agda#1731.
I guess nobody tests UHC on Windows, but maybe you know something more?

If nobody tests it, I think the cygwin support should be marked as unmaintained/untested on [UHC - WebHome](http://foswiki.cs.uu.nl/foswiki/UHC).

**Comment by atzedijkstra** [comment]
Indeed there is currently not somebody maintaining the Windows/cygwin combi. I'll update the wiki.

A
