### ISSUE TITLE
uhc-light-1.1.9.2 build error

### ISSUE THREAD

**Issue by peti** [UU-ComputerScience/uhc#69]
Citing from http://hydra.cryp.to/build/1550395/log/raw:

~~~~
src/ehc/Base/Common.chs:106:10:
    Duplicate instance declarations:
      instance Hashable Version
        -- Defined at src/ehc/Base/Common.chs:106:10
      instance Hashable Version
        -- Defined in ‘hashable-1.2.4.0:Data.Hashable.Class’
~~~~~

**Comment by peti** [comment]
uhc-1.1.9.2 has the same issue: http://hydra.cryp.to/build/1551821/log/raw.

**Comment by atzedijkstra** [comment]
Version 1.2.4 of hashable introduces the new instance. I have updated the hackage versions of uhc-util and uhc to constrain hashable < 1.2.4

**Comment by peti** [comment]
Unfortunately,  that will not allow us (NixOS) to build and distribute the package; it just gives us a better error message. :-(

**Comment by atzedijkstra** [comment]
The next version will have this fixed, that is, include a version constraint >= 1.2.4, but that obviously will not help uhc-1.1.9.2. This is a recurring and unfixable problem as it is the context in which uhc compiles which makes uhc compilation break, as such rather unpredictable and at the mercy of other packages :-).

**Comment by phile314** [comment]
Just for the record, UHC builds fine with Stackage LTS 4.1. Later LTS versions contain a newer hashable version and don't work for UHC 1.1.9.2.

**Comment by asr** [comment]
+1

**Comment by atzedijkstra** [comment]
New release 1.1.9.3 has been put on hackage, along with uhc-util-0.1.6.5, should be ok now

**Comment by asr** [comment]
Thanks!
