### ISSUE TITLE
Missing support for GHC 8

### ISSUE THREAD

**Issue by asr** [UU-ComputerScience/uhc#71]
Using GHC 8.0.1 RC 2:

```
$ cabal unpack uhc-light
$ cd uhc-light-1.1.9.2
$ cabal sandbox init
$ cabal install
...
rejecting: hashable-1.2.4.0 (conflict: uhc-light => hashable>=1.1 && <1.2.4)
...
Dependency tree exhaustively searched.
```

hashable 1.2.4 is required with GHC 8 but it was removed in #69.

**Comment by atzedijkstra** [comment]
New release 1.1.9.3 has been put on hackage, along with uhc-util-0.1.6.5, along with a version constraint for hashable >= 1.2.4. Not sure whether there is more needed to make it compile/work for ghc 8 as I do not have a ghc8 release available for testing...

**Comment by asr** [comment]
> Not sure whether there is more needed to make it compile/work for ghc 8 as I do not have a ghc8 release available for testing...

I made the test.  I created the PR https://github.com/atzedijkstra/logict-state/pull/1.

**Comment by asr** [comment]
> Not sure whether there is more needed to make it compile/work for ghc 8 as I do not have a ghc8 release available for testing...

I made the test. See https://github.com/UU-ComputerScience/uhc-util/issues/8#issuecomment-186636197.

**Comment by asr** [comment]
After the fix  for https://github.com/UU-ComputerScience/uhc-util/issues/8 there are new problems. From your comment https://github.com/UU-ComputerScience/uhc/issues/73#issuecomment-187059603, I will report these problems as UHC problems.

**Comment by asr** [comment]
What version of UHC should I use for reporting the issues? The current [released](https://github.com/UU-ComputerScience/uhc/releases/tag/v1.1.9.3) version? The master branch? Other branch?

**Comment by atzedijkstra** [comment]
Reporting an issue against a release or master head version is both fine. If there is a fix or pull request it is preferrable to have this for the master head.

--
Atze Dijkstra

**Comment by asr** [comment]
Using GHC 8.0.1 RC 2 and master head version (commit aabb6a7):

```
$ cd EHC
$./configure
$ make
...
[ 23 of 247] Compiling UHC.Compiler.Base.Common ( UHC/Compiler/Base/Common.hs, dist/build/UHC/Compiler/Base/Common.o )

src/ehc/Base/Common.chs:92:1: error:
    Duplicate instance declarations:
      instance Generic Version -- Defined at src/ehc/Base/Common.chs:92:1
      instance [safe] Generic Version -- Defined in ‘Data.Version’
```

**Comment by atzedijkstra** [comment]
I have added a check on the compiler version around this code.

**Comment by asr** [comment]
Thanks. I got the same issue described [here](https://github.com/UU-ComputerScience/uhc/issues/74#issuecomment-189966071) when using GHC 8.0.1 RC 2.

**Comment by asr** [comment]
I got many compilation errors on `src/ehc/EHC/BuildFunction/Run.chs`. It seems related to a GHC 8.0.1 RC 2 bug (which was fixed in upstream) involving `ImpredicativeTypes`.

**Comment by asr** [comment]
How I run the test-suite?

**Comment by asr** [comment]
I created the PR #76.

**Comment by asr** [comment]
> I got many compilation errors on src/ehc/EHC/BuildFunction/Run.chs. It seems related to a GHC 8.0.1 RC 2 bug (which was fixed in upstream) involving ImpredicativeTypes.

I got the same errors using GHC 8.0.1. Please merge the PR #76.

**Comment by atzedijkstra** [comment]
I usually run the test suite for variant 100:

make 100/ehc
make 100/ehclib
make test-regress TEST_VARIANTS=100

This expects that a previous run of the test suite has been done to create the output against which is compared:

make test-expect TEST_VARIANTS=100

Currently the results of such a previous run are not stored in the repo (no need for that currently/until now).
Substitute 'uhc' for '100' in case you want to do this for uhc:

make 
make test-regress TEST_VARIANTS=uhc

**Comment by asr** [comment]
I had no problem building uhc using GHC 7.10.8 or GHC 8.0.1. I'm running the tests...

**Comment by asr** [comment]
It seems the tests were ok with both versions of GHC:

```
$ make test-regress TEST_VARIANTS=uhc
...
== completed with 0 errors, 0 (probably) platform dependent errors, and 149 warnings ==
```

**Comment by asr** [comment]
Are you ready for realising to Hackage?

**Comment by atzedijkstra** [comment]
I am running various build/installation checks now :-).

A

**Comment by asr** [comment]
Great!

**Comment by asr** [comment]
I am testing the UHC compiler backend in Agda...

**Comment by asr** [comment]
I cannot test the UHC compiler backend in Agda because I have no `uhc-ligth-1.1.9.4`.

**Comment by atzedijkstra** [comment]
Is uploaded to hackage now. Success :-)!

A

**Comment by asr** [comment]
Yep!
