### ISSUE TITLE
putStr[Ln] can't handle Unicode

### ISSUE THREAD

**Issue by asr** [UU-ComputerScience/uhc#72]
```
$ uhc --version
ehc-1.1.9.2, revision @, timestamp 20151212 -0500 164801

$ cat Test.hs
main :: IO ()
main = putStrLn "BEFORE ∀ AFTER"

$ uhc Test.hc
$ ./Test
BEFORE
```

**Comment by atzedijkstra** [comment]
There is indeed no support for unicode.

**Comment by phile314** [comment]
I assume unicode support is not coming anytime soon? Just asking so that I can update the Agda manual accordingly.

**Comment by atzedijkstra** [comment]
Currently (indeed) other source code changes have higher priority, for the time being there will be no unicode support (unless somebody else will work on this :-))

**Comment by asr** [comment]
Blocking https://github.com/agda/agda/issues/1857.

**Comment by atzedijkstra** [comment]
Partial support for unicode has been added:
- string constants may hold unicode chars
- chars were internally already represented by Int
- putChar family of functions writes utf8 for char

Not done:
- getChar family

**Comment by asr** [comment]
Thanks!
