### ISSUE TITLE
Separate bug trackers for UHC and uhc-light

### ISSUE THREAD

**Issue by asr** [UU-ComputerScience/uhc#73]
I'm not familiar with the UHC system, but I suggest to use separate bug trackers for UHC and uhc-light.

**Comment by atzedijkstra** [comment]
Lib uhc-light is generated from UHC sources, so there is not a separate repository, bug fixes are done in UHC and then propagate to uhc-light. Pull requests on uhc-light would therefore be unhandy to merge; hence the current setup.

**Comment by asr** [comment]
Thanks for the explanation.
