### ISSUE TITLE
-O0 broken

### ISSUE THREAD

**Issue by phile314** [UU-ComputerScience/uhc#74]
<pre>
module Test
where

import Prelude

data QName = QName { nameId, moduleId ::Integer, qnameString :: String }

instance Eq QName where
  (QName a b _) == (QName c d _) = (a, b) == (c, d)

main :: IO ()
main = return ()
</pre>

<pre>
uhc Test.hs -O0
[1/1] Compiling Haskell                  Test                   (Test.hs)
Grin to ByteCode
(Internal) GRIN ByteCode location names not in scope:
  UHC.Base.primAddInt
</pre>

version: 1.1.9.3

**Comment by atzedijkstra** [comment]
Should be ok now

**Comment by asr** [comment]
I couldn't test the fix because using GHC 7.10.3 and master in 230d6c8 I got various errors. The first one is

```
$ make clean
$ ./configure
$ make
...
[177 of 247] Compiling UHC.Compiler.Pred.ToCHR ( UHC/Compiler/Pred/ToCHR.hs, dist/build/UHC/Compiler/Pred/ToCHR.o )

src/ehc/Pred/ToCHR.chs:214:24:
    Couldn't match expected type ‘[b1]
                                  -> ([c2], [c2], SolveTrace FIIn Constraint Guard Prio VarMp)’
                with actual type ‘([c1],
                                   [c1],
                                   UHC.Util.CHR.Solve.TreeTrie.Mono.SolveTrace c1 g1 p1 s1)’
Relevant bindings include
      superClassesWork :: [c2] (bound at src/ehc/Pred/ToCHR.chs:213:10)
      superClassesDone :: [c2] (bound at src/ehc/Pred/ToCHR.chs:213:28)
    The function ‘chrSolve'’ is applied to four arguments,
    but its type ‘[t1]
                  -> UHC.Util.CHR.Solve.TreeTrie.Mono.CHRStore c1 g1 p1
                  -> [c1]
                  -> ([c1],
                      [c1],
                      UHC.Util.CHR.Solve.TreeTrie.Mono.SolveTrace c1 g1 p1 s1)’
    has only three
    In the expression:
      chrSolve'
        []
        env
        rules
        (map
           (\ p -> toSolverConstraint $ mkAssume $ mkCHRPredOcc p sc1)
           context)
    In a pattern binding:
      (superClassesWork,
       superClassesDone,
       _ :: SolveTrace FIIn Constraint Guard Prio VarMp)
        = chrSolve'
            []
            env
            rules
            (map
               (\ p -> toSolverConstraint $ mkAssume $ mkCHRPredOcc p sc1)
               context)
```

**Comment by atzedijkstra** [comment]
Ah, I forgot to run 'autoconf', uhc-util>=0.1.6.6 is required (which is currently only in its repo). I keep the uhc and uhc-util repo in sync, avoiding updates to hackage as not to confuse some nix installations (which seems to pick only the latest versions available on hackage, even if cabal files specifies not to do so). But this then means both uhc and uhc-util have to be used from their repos jointly.

**Comment by asr** [comment]
Why not remove the files generated by `autoconf` from the repo?

**Comment by asr** [comment]
The new compilation error is

```
$ make clean
$ ./configure
$ make
...
[174 of 247] Compiling UHC.Compiler.CHR.Solve ( UHC/Compiler/CHR/Solve.hs, dist/build/UHC/Compiler/CHR/Solve.o )

src/ehc/CHR/Key.chs:138:15:
    Conflicting family instance declarations:
      UHC.Util.TreeTrie.TrTrKey x
        -- Defined at src/ehc/CHR/Key.chs:138:15
      UHC.Util.TreeTrie.TrTrKey (Rule cnstr guard prio)
        -- Defined in ‘UHC.Util.CHR.Rule’
```

**Comment by atzedijkstra** [comment]
Removing the configure means another dependency, on autoconf, which is not present by default on all OS's. Usually no problem, i.e. I usually don't forget this :-).

I have replaced the problematic type family instance with an equality constraint and a less general instance. Not sure why it did work in the first place anyway...

**Comment by asr** [comment]
From the commit message:

> fix for (ghc 8 erroneous) type family instance

FYI, I got the error using GHC 7.10.3.

Testing...

**Comment by asr** [comment]
Now I got the error:

```
$ libtool --version
libtool (GNU libtool) 2.4.2
```

```
$ make
...
libtool: unrecognized option `-static'
```

**Comment by atzedijkstra** [comment]
Ok, I am using GHC 7.10.2...

Hmn, libtool, so can I assume the GHC part did compile? For the libtool part, this usually is something OS dependent, what system are you running on?

**Comment by asr** [comment]
> so can I assume the GHC part did compile?

Yes.

> For the libtool part, this usually is something OS dependent, what system are you running on?

Ubuntu 12.04 64-bits.

**Comment by atzedijkstra** [comment]
configure.ac/configure checks for the host platform to choose whether or not to use libtool. You might tweak that part (approx at line 1139) a bit. UHC used to compile without problems under Ubuntu, but I have not checked this lately. Let me know whether you can find a solution; if not I'll look into it later when I have some more time.

**Comment by asr** [comment]
Which is your output for the command `libtool --version`?

> UHC used to compile without problems under Ubuntu, but I have not checked this lately.

You are right. I could install 1.1.9.3 without problems.

**Comment by asr** [comment]
In a fresh repo, I couldn't reproduce the problem with `libtool`. Sorry for the noise.

**Comment by asr** [comment]
The issue with `-O0` was fixed. Thanks!
