### ISSUE TITLE
UHC prints doubles with lower precision than GHC

### ISSUE THREAD

**Issue by asr** [UU-ComputerScience/uhc#87]
```haskell
main = print $ sqrt (2.0 :: Double)
```

With GHC (8.0.1): `1.4142135623730951`
with UHC: `1.414214`

Is there any reason for the difference?

Blocking https://github.com/agda/agda/issues/1856.

**Comment by atzedijkstra** [comment]
History. UHC libs are taken from an old GHC library version. I have adapted the printing of Double to show more precision. The format is not a replica of what GHC does but at least closer to it; it is delegated to the runtime system.

**Comment by asr** [comment]
> The format is not a replica of what GHC does but at least closer to it;
Right:

GHC (8.0.1): `1.4142135623730951`
UHC (cdd8252): `1.414213562373095`

Thanks!

**Comment by asr** [comment]
When printing `1.0`:

UHC 1.1.9.4 prints: `1.000000` 
UHC 1.1.9.5 prints: `1`.

Is it the expected behaviour? 

FWIW, GHC 8.0.1 prints `1.0`.
