### ISSUE TITLE
(8 Core) Case default broken?

### ISSUE THREAD

**Issue by Frans-Willem** [UU-ComputerScience/uhc#88]
Currently the following code
```haskell
main =
  case 4 of
    1 -> 123
    2 -> 456
    3 -> 789
    _ -> 999
```
turns into this core representation (before any transformations):
```haskell
let
  main
    = let
        $$`${0$,30$,1$}
          = #Int"4"; in
      let
        $$`${0$,33$,1$}$`$`CCN${$}
          = #Int"999"; in
      let !
        $$`${0$,30$,1$}$`$`EVL${$}
          = $$`${0$,30$,1$}; in
      case $$`${0$,30$,1$}$`$`EVL${$} of
       #Int"1" ->
         #Int"123";
       #Int"2" ->
         #Int"456";
       #Int"3" ->
         #Int"789";
       default
         $$?$?;; in
main
```

Note how the default is still compiled, yet not referenced at all from the case statement.

After the transformations and optimizations, the final code boils down to:
```haskell
module case2;
let
  main
    = case #Int"4" of
       #Int"1" ->
         #Int"123";
       #Int"2" ->
         #Int"456";
       #Int"3" ->
         #Int"789";
       default
         $$?$?;; in
main
```

Seeing the default completely disappear...

Any help on why this is happening, or how to fix it ?

**Comment by atzedijkstra** [comment]
De dafault branch of the case expression is artefact of early experiments and is not used. It should be used (to more compactly represent case branches) or be removed;neither has been done so it can be ignored.
