### ISSUE TITLE
Request: Addition to Stackage

### ISSUE THREAD

**Issue by asr** [UU-ComputerScience/uhc#91]
We are planning to build Agda using Stackage. Please consider to add pqueue to Stackage. See  instructions [here](https://github.com/fpco/stackage#add-your-package).

**Comment by asr** [comment]
Blocking https://github.com/agda/agda/issues/2396.

**Comment by atzedijkstra** [comment]
Hi Andres,

As I have no experience with Stackage myself, perhaps you (or somebody in your environment) could help out with this series (similar for uulib, uhc-util etc) of requests, subsequent modifications to the relevant repo (made available as a pull request) would be the most helpful :-)!

regards,
Atze

**Comment by asr** [comment]
I'm closing the issue because we are making the Agda UHC backend a stand-alone product.
